export const publicRoutes = [
  {
    path: '/',
    name: 'Home',
    component: () => import('../../views/Home.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/shops/',
    name: 'Shops',
    component: () => import('../../views/shops/Shops.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/shops/:slug/:id/',
    name: 'ShopDetails',
    component: () => import('../../views/shops/ShopDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/publishers/',
    name: 'Publishers',
    component: () => import('../../views/publishers/Publishers.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/publishers/:slug/:id/',
    name: 'PublisherDetails',
    component: () => import('../../views/publishers/PublisherDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/categories/',
    name: 'Categories',
    component: () => import('../../views/categories/Categories.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/category/:slug/:id/',
    name: 'CategoryDetails',
    component: () => import('../../views/categories/CategoryDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/sub-category/:slug/:id/',
    name: 'ChildCategoryDetails',
    component: () =>
      import('../../views/childCategories/ChildCategoryDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/sub-sub-category/:slug/:id/',
    name: 'SubChildCategoryDetails',
    component: () =>
      import('../../views/subChildCategories/SubChildCategoryDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/collections/',
    name: 'Collections',
    component: () => import('../../views/collections/Collections.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/collections/:slug/:id/',
    name: 'CollectionDetails',
    component: () => import('../../views/collections/CollectionDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/campaigns/',
    name: 'Campaigns',
    component: () => import('../../views/campaigns/Campaigns.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/campaign/:slug/:id/',
    name: 'CampaignDetails',
    component: () => import('../../views/campaigns/CampaignDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/product/flash/',
    name: 'ProductFlash',
    component: () => import('../../views/product/Flash.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/product/new/',
    name: 'ProductNew',
    component: () => import('../../views/product/New.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/products/',
    name: 'Products',
    component: () => import('../../views/product/Products.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/product/:slug/:id/',
    name: 'ProductDetails',
    component: () => import('../../views/product/ProductDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/brands/',
    name: 'Brands',
    component: () => import('../../views/brands/Brands.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/brands/:slug/:id/',
    name: 'BrandDetails',
    component: () => import('../../views/brands/BrandDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/authors/',
    name: 'Authors',
    component: () => import('../../views/authors/Authors.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/authors/:slug/:id/',
    name: 'AuthorDetails',
    component: () => import('../../views/authors/AuthorDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/scan/',
    name: 'Scan',
    component: () => import('../../views/product/Scan.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/page/:slug/',
    name: 'PageDetails',
    component: () => import('../../views/page/PageDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
  {
    path: '/about/',
    name: 'About',
    component: () => import('../../views/page/PageDetails.vue'),
    meta: { keepalive: true, requiresAuth: false },
  },
]
